CREATE DATABASE [oneglobal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'oneglobal', FILENAME = N'/var/opt/mssql/data/oneglobal.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'oneglobal_log', FILENAME = N'/var/opt/mssql/data/oneglobal_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [oneglobal] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [oneglobal] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [oneglobal] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [oneglobal] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [oneglobal] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [oneglobal] SET ARITHABORT OFF 
GO
ALTER DATABASE [oneglobal] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [oneglobal] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [oneglobal] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [oneglobal] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [oneglobal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [oneglobal] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [oneglobal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [oneglobal] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [oneglobal] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [oneglobal] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [oneglobal] SET  DISABLE_BROKER 
GO
ALTER DATABASE [oneglobal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [oneglobal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [oneglobal] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [oneglobal] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [oneglobal] SET  READ_WRITE 
GO
ALTER DATABASE [oneglobal] SET RECOVERY FULL 
GO
ALTER DATABASE [oneglobal] SET  MULTI_USER 
GO
ALTER DATABASE [oneglobal] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [oneglobal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [oneglobal] SET DELAYED_DURABILITY = DISABLED 
GO

USE [oneglobal]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [oneglobal]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [oneglobal] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
