using System.Text.Json.Serialization;

namespace OneGlobalDevicesApi.Domain.Common
{
    /// <summary>
    /// Represents a problem details object as defined in RFC 9457 (Problem Details for HTTP APIs).
    /// https://www.rfc-editor.org/rfc/rfc9457.html
    /// </summary>
    public record ProblemDetails
    {
        /// <summary>
        /// A URI reference (RFC3986) that identifies the problem type.
        /// When dereferenced, it SHOULD provide human-readable documentation for the problem type.
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get; init; } = "about:blank";

        /// <summary>
        /// A short, human-readable summary of the problem type.
        /// It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; init; } = string.Empty;

        /// <summary>
        /// The HTTP status code generated by the origin server for this occurrence of the problem.
        /// </summary>
        [JsonPropertyName("status")]
        public int Status { get; init; }

        /// <summary>
        /// A human-readable explanation specific to this occurrence of the problem.
        /// </summary>
        [JsonPropertyName("detail")]
        public string? Detail { get; init; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem.
        /// It may or may not yield further information if dereferenced.
        /// </summary>
        [JsonPropertyName("instance")]
        public string? Instance { get; init; }

        /// <summary>
        /// Optional extension members to provide additional information about the problem.
        /// </summary>
        [JsonExtensionData]
        public Dictionary<string, object>? Extensions { get; init; }

        /// <summary>
        /// Creates a ProblemDetails instance for a Bad Request (400) error.
        /// </summary>
        public static ProblemDetails BadRequest(string detail, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc9110#section-15.5.1",
                Title = "Bad Request",
                Status = StatusCodes.Status400BadRequest,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }

        /// <summary>
        /// Creates a ProblemDetails instance for a Not Found (404) error.
        /// </summary>
        public static ProblemDetails NotFound(string detail, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc9110#section-15.5.5",
                Title = "Not Found",
                Status = StatusCodes.Status404NotFound,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }

        /// <summary>
        /// Creates a ProblemDetails instance for an Internal Server Error (500) error.
        /// </summary>
        public static ProblemDetails InternalServerError(string detail, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc9110#section-15.6.1",
                Title = "Internal Server Error",
                Status = StatusCodes.Status500InternalServerError,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }

        /// <summary>
        /// Creates a ProblemDetails instance for a Conflict (409) error.
        /// </summary>
        public static ProblemDetails Conflict(string detail, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc9110#section-15.5.10",
                Title = "Conflict",
                Status = StatusCodes.Status409Conflict,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }

        /// <summary>
        /// Creates a ProblemDetails instance for an Unprocessable Entity (422) error.
        /// </summary>
        public static ProblemDetails UnprocessableEntity(string detail, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = "https://tools.ietf.org/html/rfc4918#section-11.2",
                Title = "Unprocessable Entity",
                Status = StatusCodes.Status422UnprocessableEntity,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }

        /// <summary>
        /// Creates a custom ProblemDetails instance with specified parameters.
        /// </summary>
        public static ProblemDetails Create(int status, string title, string type, string? detail = null, string? instance = null, Dictionary<string, object>? extensions = null)
        {
            return new ProblemDetails
            {
                Type = type,
                Title = title,
                Status = status,
                Detail = detail,
                Instance = instance,
                Extensions = extensions
            };
        }
    }
}
